// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkascbiqquujlbqcpfrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrYXNjYmlxcXV1amxicWNwZnJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzA3MTcsImV4cCI6MjA2Mzk0NjcxN30.N8yDrZ9dQRsd6CgOtnCyivoddgVilrO9vEz8AFt_7YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);